name = "collection-discount-ui"
uid = "e855f5bf-3a04-244a-289a-7c2fb68f52f81cbf4cf3"
type = "ui_extension"
api_version = "2025-07"

[[targeting]]
target = "admin.discount-details.function-settings.render"
module = "./src/index.tsx"

[[targeting.metafields]]
namespace = "$app"
key = "function-configuration"
type = "json"
access.admin = "merchant_read_write"
