name = "collection-discount-rs"
uid = "92f713a9-62f3-a232-edb8-0f7022fd729c1881d669"
type = "function"
description = "Collection-based percentage discount function"
api_version = "2026-04"

[build]
command = "build.bat"
path = "target/wasm32-wasip1/release/collection-discount-rs.wasm"

[[targeting]]
target = "cart.lines.discounts.generate.run"

[[targeting]]
target = "cart.delivery-options.discounts.generate.run"

[discount]
class = ["product", "order", "shipping"]
